package com.onedeepath.negooxtools.productsList

data class Products(val id: Int,
                    val productName: String,
                    var totalPriceBuy: Float,
                    val dateOfBuy: String,
                    var priceProduct: Float,
                    val weightProduct: Float,
                    val courierName: String,
                    var courierTax: Float,
                    val cardName: String,
                    var cardTax: Float,
                    val webName: String,
                    var webTax: Float,
                    var paypalTax: Float,
                    var totalPriceSale: Float,
                    val dateOfSale: String,
                    var deliveryCost: Float,
                    val delayArrival: Int,
                    val delaySale: Int,
                    var profit: Float,
                    val category: String)
